module.exports = {
  apps: [{
    name: 'ai24x02',
    script: 'server-3002.js',
    cwd: __dirname,
    instances: 1,
    autorestart: true,
    watch: true,
    watch_delay: 1000,
    ignore_watch: [
      'node_modules',
      'logs',
      '.git',
      '*.log',
      '*.bat',
      '*.ps1',
      '*.md'
    ],
    max_memory_restart: '500M',
    env: {
      NODE_ENV: 'production',
      PORT: 3002
    },
    env_development: {
      NODE_ENV: 'development',
      PORT: 3002
    },
    error_file: 'logs/ai24x02-error.log',
    out_file: 'logs/ai24x02-out.log',
    log_file: 'logs/ai24x02-combined.log',
    time: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    min_uptime: '10s',
    max_restarts: 10,
    restart_delay: 5000,
    kill_timeout: 5000,
    listen_timeout: 10000,
    shutdown_with_message: false,
    wait_ready: false,
    source_map_support: true,
    instance_var: 'INSTANCE_ID',
    exec_mode: 'fork',
    interpreter: 'node',
    interpreter_args: '',
    cron_restart: '',
    vizion: true,
    post_update: [],
    force: false,
    next_gen_js: false,
    vizion_run: true,
    filter_env: [],
    autorestart_delay: 0,
    treekill: true,
    windowsHide: true,
    kill_retry_time: 100,
    exit_code: 0,
    stop_exit_codes: [0],
    stop_signal: 'SIGTERM',
    ready_signal: 'ready',
    pre_restart: [],
    post_restart: [],
    pre_start: [],
    post_start: [],
    pre_stop: [],
    post_stop: [],
    env_stop: {}
  }]
};