from __future__ import annotations

import os
import time
from datetime import date
from datetime import datetime, timezone, timedelta
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, Iterator, Optional

import json
import secrets

from .config import settings


def _ensure_parent_dir(path: str) -> None:
    parent = os.path.dirname(os.path.abspath(path))
    os.makedirs(parent, exist_ok=True)


def _is_pg() -> bool:
    return str(getattr(settings, "db_kind", "sqlite") or "sqlite").strip().lower() in ("pg", "pgsql", "postgres", "postgresql")


def _adapt_sql(sql: str) -> str:
    """
    sqlite3 uses `?` parameters while psycopg uses `%s`.
    This adapter keeps the existing MVP SQL readable and swaps placeholders only for Postgres.
    """
    if not _is_pg():
        return sql
    return sql.replace("?", "%s")


def _row_get(row: Any, key: str) -> Any:
    """
    sqlite3.Row supports `row["k"]` but not `.get()`;
    psycopg dict_row returns dict-like rows with `.get()`.
    """
    try:
        if hasattr(row, "get"):
            return row.get(key)  # type: ignore[attr-defined]
    except Exception:
        pass
    try:
        return row[key]
    except Exception:
        return None


def _cfg_int(key: str, default: int) -> int:
    """
    Read integer config from admin_config (DB) with fallback to default.
    Empty / invalid values are treated as missing.
    """
    try:
        v = admin_config_get(key)
        if v is None:
            return int(default)
        s = str(v).strip()
        if s == "":
            return int(default)
        return int(float(s))
    except Exception:
        return int(default)


def invite_cfg_effective() -> dict[str, int]:
    """Effective invite reward config (admin_config overrides env defaults)."""
    return {
        "invite_reward_inviter_weekly": _cfg_int(
            "invite_reward_inviter_weekly", int(getattr(settings, "invite_reward_inviter_weekly", 100) or 100)
        ),
        "invite_reward_invitee_weekly": _cfg_int(
            "invite_reward_invitee_weekly", int(getattr(settings, "invite_reward_invitee_weekly", 50) or 50)
        ),
        "invite_weekly_cap": _cfg_int(
            "invite_weekly_cap", int(getattr(settings, "invite_weekly_cap", 500) or 500)
        ),
        "invite_reward_inviter_daily": _cfg_int(
            "invite_reward_inviter_daily", int(getattr(settings, "invite_reward_inviter_daily", 0) or 0)
        ),
        "invite_reward_invitee_daily": _cfg_int(
            "invite_reward_invitee_daily", int(getattr(settings, "invite_reward_invitee_daily", 0) or 0)
        ),
    }


class _ConnProxy:
    """
    Uniform DB API for sqlite3/psycopg connections.
    - Auto-adapts placeholder style (`?` -> `%s`) for Postgres.
    - Keeps the existing MVP code mostly unchanged.
    """

    def __init__(self, conn: Any):
        self._conn = conn

    def execute(self, sql: str, params: Any = ()) -> Any:
        return self._conn.execute(_adapt_sql(sql), params)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._conn, name)


@contextmanager
def connect() -> Iterator[Any]:
    if _is_pg():
        try:
            import psycopg  # type: ignore
            from psycopg.rows import dict_row  # type: ignore
        except Exception as e:
            raise RuntimeError("PostgreSQL mode requires psycopg. Install dependencies first.") from e

        dsn = str(getattr(settings, "database_url", "") or "").strip()
        if not dsn:
            raise RuntimeError("AI24X_DATABASE_URL is required when AI24X_DB_KIND=pgsql")

        conn = psycopg.connect(dsn, autocommit=False, row_factory=dict_row)
        try:
            yield _ConnProxy(conn)
            conn.commit()
        finally:
            try:
                conn.close()
            except Exception:
                pass
        return

    # sqlite (default)
    import sqlite3  # local import to avoid forcing sqlite in pg envs

    _ensure_parent_dir(settings.db_path)
    conn = sqlite3.connect(settings.db_path, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        yield _ConnProxy(conn)
        conn.commit()
    finally:
        conn.close()


def init_db() -> None:
    with connect() as conn:
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  email TEXT UNIQUE,
                  phone TEXT UNIQUE,
                  created_at BIGINT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS quota (
                  user_id BIGINT PRIMARY KEY,
                  plan TEXT NOT NULL DEFAULT 'free',
                  monthly_limit BIGINT NOT NULL,
                  daily_limit BIGINT NOT NULL,
                  monthly_used BIGINT NOT NULL DEFAULT 0,
                  daily_used BIGINT NOT NULL DEFAULT 0,
                  month_key TEXT NOT NULL,
                  day_key TEXT NOT NULL,
                  expires_at BIGINT,
                  updated_at BIGINT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS invite_codes (
                  user_id BIGINT PRIMARY KEY,
                  code TEXT UNIQUE NOT NULL,
                  created_at BIGINT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS invite_relations (
                  invitee_id BIGINT PRIMARY KEY,
                  inviter_id BIGINT NOT NULL,
                  created_at BIGINT NOT NULL
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS quota_ledger (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id BIGINT NOT NULL,
                  secid TEXT NOT NULL,
                  period TEXT NOT NULL,
                  idempotency_key TEXT NOT NULL,
                  consumed_at BIGINT NOT NULL,
                  result TEXT NOT NULL,
                  UNIQUE(user_id, idempotency_key)
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS reward_ledger (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  inviter_id BIGINT NOT NULL,
                  invitee_id BIGINT NOT NULL,
                  reward_type TEXT NOT NULL,
                  amount BIGINT NOT NULL,
                  created_at BIGINT NOT NULL,
                  UNIQUE(inviter_id, invitee_id, reward_type)
                );
                """
            )

            # Minimal indexes (PG): keep query paths fast under real traffic.
            # - invite list/summary: filter by inviter_id
            # - ledgers: frequent per-user queries by time
            # - cache: enable future cleanup by expire_ts
            conn.execute("CREATE INDEX IF NOT EXISTS idx_invite_relations_inviter_id ON invite_relations(inviter_id);")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_quota_ledger_user_time ON quota_ledger(user_id, consumed_at DESC);")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_reward_ledger_inviter_time ON reward_ledger(inviter_id, created_at DESC);")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_reward_ledger_inviter_type_time ON reward_ledger(inviter_id, reward_type, created_at DESC);")
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  email TEXT UNIQUE,
                  phone TEXT UNIQUE,
                  created_at INTEGER NOT NULL
                );
                """
            )
            # Soft-migration: older DBs may lack email column (sqlite only)
            try:
                cols = [r["name"] for r in conn.execute("PRAGMA table_info(users)").fetchall()]
                if "email" not in cols:
                    conn.execute("ALTER TABLE users ADD COLUMN email TEXT")
                    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email)")
            except Exception:
                pass

            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS quota (
                  user_id INTEGER PRIMARY KEY,
                  plan TEXT NOT NULL DEFAULT 'free',
                  monthly_limit INTEGER NOT NULL,
                  daily_limit INTEGER NOT NULL,
                  monthly_used INTEGER NOT NULL DEFAULT 0,
                  daily_used INTEGER NOT NULL DEFAULT 0,
                  month_key TEXT NOT NULL,
                  day_key TEXT NOT NULL,
                  expires_at INTEGER,
                  updated_at INTEGER NOT NULL,
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS invite_codes (
                  user_id INTEGER PRIMARY KEY,
                  code TEXT UNIQUE NOT NULL,
                  created_at INTEGER NOT NULL,
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS invite_relations (
                  invitee_id INTEGER PRIMARY KEY,
                  inviter_id INTEGER NOT NULL,
                  created_at INTEGER NOT NULL,
                  FOREIGN KEY(invitee_id) REFERENCES users(id),
                  FOREIGN KEY(inviter_id) REFERENCES users(id)
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS quota_ledger (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  user_id INTEGER NOT NULL,
                  secid TEXT NOT NULL,
                  period TEXT NOT NULL,
                  idempotency_key TEXT NOT NULL,
                  consumed_at INTEGER NOT NULL,
                  result TEXT NOT NULL,
                  UNIQUE(user_id, idempotency_key),
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS reward_ledger (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  inviter_id INTEGER NOT NULL,
                  invitee_id INTEGER NOT NULL,
                  reward_type TEXT NOT NULL,
                  amount INTEGER NOT NULL,
                  created_at INTEGER NOT NULL,
                  UNIQUE(inviter_id, invitee_id, reward_type),
                  FOREIGN KEY(inviter_id) REFERENCES users(id),
                  FOREIGN KEY(invitee_id) REFERENCES users(id)
                );
                """
            )

        # Market data cache (MVP): persist successful K-line payloads for resilience across restarts.
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS kline_cache (
              cache_key TEXT PRIMARY KEY,
              expire_ts BIGINT NOT NULL,
              payload_json TEXT NOT NULL,
              updated_at BIGINT NOT NULL
            );
            """
        )
        if _is_pg():
            conn.execute("CREATE INDEX IF NOT EXISTS idx_kline_cache_expire_ts ON kline_cache(expire_ts);")

        # Admin runtime config (MVP): key-value overrides for ops (e.g. paid provider switch/priority)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS admin_config (
              key TEXT PRIMARY KEY,
              value TEXT NOT NULL,
              updated_at BIGINT NOT NULL
            );
            """
        )

        # 后台分管预留：启用行手机号可与 AI24X_ADMIN_OTP_PHONES 并集参与 OTP 登录；perm_flags/perm_json 预留细粒度权限
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_operators (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  phone TEXT NOT NULL UNIQUE,
                  display_name TEXT,
                  role TEXT NOT NULL DEFAULT 'deputy',
                  enabled BIGINT NOT NULL DEFAULT 1,
                  perm_flags BIGINT NOT NULL DEFAULT 0,
                  perm_json TEXT,
                  invited_by TEXT,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_admin_operators_enabled ON admin_operators(enabled);")
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_operators (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  phone TEXT NOT NULL UNIQUE,
                  display_name TEXT,
                  role TEXT NOT NULL DEFAULT 'deputy',
                  enabled INTEGER NOT NULL DEFAULT 1,
                  perm_flags INTEGER NOT NULL DEFAULT 0,
                  perm_json TEXT,
                  invited_by TEXT,
                  created_at INTEGER NOT NULL,
                  updated_at INTEGER NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_admin_operators_enabled ON admin_operators(enabled);")

        # Admin ops audit log (MVP): quota/plan changes should be traceable.
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_ops_ledger (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id BIGINT NOT NULL,
                  actor TEXT NOT NULL,
                  action TEXT NOT NULL,
                  before_json TEXT NOT NULL,
                  after_json TEXT NOT NULL,
                  note TEXT NOT NULL DEFAULT '',
                  created_at BIGINT NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_admin_ops_ledger_user_time ON admin_ops_ledger(user_id, created_at DESC);")
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS admin_ops_ledger (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  user_id INTEGER NOT NULL,
                  actor TEXT NOT NULL,
                  action TEXT NOT NULL,
                  before_json TEXT NOT NULL,
                  after_json TEXT NOT NULL,
                  note TEXT NOT NULL DEFAULT '',
                  created_at INTEGER NOT NULL,
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )

        # 支付订单（微信 Native 先打通；channel 预留 alipay / paypal）
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS pay_orders (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  out_trade_no TEXT NOT NULL UNIQUE,
                  user_id BIGINT NOT NULL,
                  plan TEXT NOT NULL,
                  amount_fen BIGINT NOT NULL,
                  channel TEXT NOT NULL DEFAULT 'wechat',
                  status TEXT NOT NULL DEFAULT 'pending',
                  code_url TEXT,
                  transaction_id TEXT,
                  paid_at BIGINT,
                  referrer_user_id BIGINT,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_pay_orders_user_id ON pay_orders(user_id);")
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_pay_orders_transaction_id ON pay_orders(transaction_id);"
            )
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS pay_orders (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  out_trade_no TEXT NOT NULL UNIQUE,
                  user_id INTEGER NOT NULL,
                  plan TEXT NOT NULL,
                  amount_fen INTEGER NOT NULL,
                  channel TEXT NOT NULL DEFAULT 'wechat',
                  status TEXT NOT NULL DEFAULT 'pending',
                  code_url TEXT,
                  transaction_id TEXT,
                  paid_at INTEGER,
                  referrer_user_id INTEGER,
                  created_at INTEGER NOT NULL,
                  updated_at INTEGER NOT NULL,
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_pay_orders_user_id ON pay_orders(user_id);")
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_pay_orders_transaction_id ON pay_orders(transaction_id);"
            )
            try:
                conn.execute("CREATE INDEX IF NOT EXISTS idx_pay_orders_referrer_user_id ON pay_orders(referrer_user_id);")
            except Exception:
                pass

        # Soft-migration: add new columns to existing pay_orders tables.
        if _is_pg():
            try:
                conn.execute("ALTER TABLE pay_orders ADD COLUMN IF NOT EXISTS paid_at BIGINT;")
            except Exception:
                pass
            try:
                conn.execute("ALTER TABLE pay_orders ADD COLUMN IF NOT EXISTS referrer_user_id BIGINT;")
            except Exception:
                pass
            try:
                conn.execute("CREATE INDEX IF NOT EXISTS idx_pay_orders_referrer_user_id ON pay_orders(referrer_user_id);")
            except Exception:
                pass
        else:
            try:
                cols = [r["name"] for r in conn.execute("PRAGMA table_info(pay_orders)").fetchall()]
                if "paid_at" not in cols:
                    conn.execute("ALTER TABLE pay_orders ADD COLUMN paid_at INTEGER")
                if "referrer_user_id" not in cols:
                    conn.execute("ALTER TABLE pay_orders ADD COLUMN referrer_user_id INTEGER")
                conn.execute("CREATE INDEX IF NOT EXISTS idx_pay_orders_referrer_user_id ON pay_orders(referrer_user_id);")
            except Exception:
                pass

        # Agent status (reserved): normal/senior/gold; currently MVP uses normal only.
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS agent_status (
                  user_id BIGINT PRIMARY KEY,
                  level TEXT NOT NULL,
                  expires_at BIGINT,
                  updated_at BIGINT NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_agent_status_level ON agent_status(level);")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_agent_status_expires_at ON agent_status(expires_at);")
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS agent_status (
                  user_id INTEGER PRIMARY KEY,
                  level TEXT NOT NULL,
                  expires_at INTEGER,
                  updated_at INTEGER NOT NULL,
                  FOREIGN KEY(user_id) REFERENCES users(id)
                );
                """
            )
            try:
                conn.execute("CREATE INDEX IF NOT EXISTS idx_agent_status_level ON agent_status(level);")
                conn.execute("CREATE INDEX IF NOT EXISTS idx_agent_status_expires_at ON agent_status(expires_at);")
            except Exception:
                pass

        # Commission ledger (MVP): manual settlement; refunds/auto-payout are reserved but disabled by default.
        if _is_pg():
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS commission_ledger (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  out_trade_no TEXT NOT NULL UNIQUE,
                  agent_user_id BIGINT NOT NULL,
                  buyer_user_id BIGINT NOT NULL,
                  plan TEXT NOT NULL,
                  amount_fen BIGINT NOT NULL,
                  rate NUMERIC NOT NULL,
                  commission_fen BIGINT NOT NULL,
                  eligible_at BIGINT NOT NULL,
                  status TEXT NOT NULL DEFAULT 'pending',
                  paid_at BIGINT,
                  paid_note TEXT NOT NULL DEFAULT '',
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL
                );
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_commission_ledger_agent_status_eligible ON commission_ledger(agent_user_id, status, eligible_at);")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_commission_ledger_status_eligible ON commission_ledger(status, eligible_at);")
        else:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS commission_ledger (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  out_trade_no TEXT NOT NULL UNIQUE,
                  agent_user_id INTEGER NOT NULL,
                  buyer_user_id INTEGER NOT NULL,
                  plan TEXT NOT NULL,
                  amount_fen INTEGER NOT NULL,
                  rate REAL NOT NULL,
                  commission_fen INTEGER NOT NULL,
                  eligible_at INTEGER NOT NULL,
                  status TEXT NOT NULL DEFAULT 'pending',
                  paid_at INTEGER,
                  paid_note TEXT NOT NULL DEFAULT '',
                  created_at INTEGER NOT NULL,
                  updated_at INTEGER NOT NULL,
                  FOREIGN KEY(agent_user_id) REFERENCES users(id),
                  FOREIGN KEY(buyer_user_id) REFERENCES users(id)
                );
                """
            )
            try:
                conn.execute("CREATE INDEX IF NOT EXISTS idx_commission_ledger_agent_status_eligible ON commission_ledger(agent_user_id, status, eligible_at);")
                conn.execute("CREATE INDEX IF NOT EXISTS idx_commission_ledger_status_eligible ON commission_ledger(status, eligible_at);")
            except Exception:
                pass


def _day_key(ts: Optional[int] = None) -> str:
    t = time.localtime(ts or int(time.time()))
    return f"{t.tm_year:04d}{t.tm_mon:02d}{t.tm_mday:02d}"


def _week_key(ts: Optional[int] = None) -> str:
    """
    ISO year-week key, e.g. 2026W15.

    Note: We intentionally reuse existing DB column names:
    - quota.month_key stores week_key
    - quota.monthly_limit/used represent weekly_limit/used
    This avoids a migration for early MVP.
    """
    d = date.fromtimestamp(ts or int(time.time()))
    iso_year, iso_week, _ = d.isocalendar()
    return f"{iso_year:04d}W{iso_week:02d}"


def _week_start_ts(ts: int) -> int:
    """UTC-like start of ISO week (Mon 00:00) using local timestamp as input.

    For MVP, we only need a stable per-week bucket for rewards. Exact timezone is not critical as
    long as it is consistent for all users in the same deployment.
    """
    d = datetime.fromtimestamp(int(ts))
    # Monday is 0
    monday = d - timedelta(days=d.weekday())
    start = datetime(monday.year, monday.month, monday.day, 0, 0, 0)
    return int(start.timestamp())


def _day_start_ts(ts: int) -> int:
    d = datetime.fromtimestamp(int(ts))
    start = datetime(d.year, d.month, d.day, 0, 0, 0)
    return int(start.timestamp())


@dataclass
class User:
    id: int
    email: str
    phone: str | None = None


def get_or_create_user_by_email(email: str, phone: str | None = None) -> User:
    now = int(time.time())
    email = (email or "").strip().lower()
    with connect() as conn:
        row = conn.execute(_adapt_sql("SELECT id, email, phone FROM users WHERE email = ?"), (email,)).fetchone()
        if row:
            email_v = _row_get(row, "email")
            phone_v = _row_get(row, "phone")
            return User(
                id=int(_row_get(row, "id") or 0),
                email=str(email_v) if email_v is not None else "",
                phone=str(phone_v) if phone_v is not None else None,
            )

        user_id: int
        if _is_pg():
            cur = conn.execute(
                "INSERT INTO users(email, phone, created_at) VALUES (%s, %s, %s) RETURNING id",
                (email, phone, now),
            )
            rr = cur.fetchone()
            user_id = int(rr["id"]) if rr and (rr.get("id") is not None) else 0
        else:
            cur = conn.execute(
                "INSERT INTO users(email, phone, created_at) VALUES (?, ?, ?)",
                (email, phone, now),
            )
            user_id = int(cur.lastrowid)
        # init quota
        if _is_pg():
            conn.execute(
                """
                INSERT INTO quota(
                  user_id, plan, monthly_limit, daily_limit,
                  monthly_used, daily_used, month_key, day_key, expires_at, updated_at
                ) VALUES (%s, 'free', %s, %s, 0, 0, %s, %s, NULL, %s)
                ON CONFLICT (user_id) DO UPDATE SET
                  plan=EXCLUDED.plan,
                  monthly_limit=EXCLUDED.monthly_limit,
                  daily_limit=EXCLUDED.daily_limit,
                  monthly_used=EXCLUDED.monthly_used,
                  daily_used=EXCLUDED.daily_used,
                  month_key=EXCLUDED.month_key,
                  day_key=EXCLUDED.day_key,
                  expires_at=EXCLUDED.expires_at,
                  updated_at=EXCLUDED.updated_at
                """,
                (user_id, settings.free_weekly, settings.free_daily_cap, _week_key(now), _day_key(now), now),
            )
        else:
            conn.execute(
                """
                INSERT INTO quota(
                  user_id, plan, monthly_limit, daily_limit,
                  monthly_used, daily_used, month_key, day_key, expires_at, updated_at
                ) VALUES (?, 'free', ?, ?, 0, 0, ?, ?, NULL, ?)
                ON CONFLICT(user_id) DO UPDATE SET
                  plan=excluded.plan,
                  monthly_limit=excluded.monthly_limit,
                  daily_limit=excluded.daily_limit,
                  monthly_used=excluded.monthly_used,
                  daily_used=excluded.daily_used,
                  month_key=excluded.month_key,
                  day_key=excluded.day_key,
                  expires_at=excluded.expires_at,
                  updated_at=excluded.updated_at
                """,
                (user_id, settings.free_weekly, settings.free_daily_cap, _week_key(now), _day_key(now), now),
            )
        return User(id=user_id, email=email, phone=phone)


def ensure_platform_user(platform_user_id: int, email: str | None, phone: str | None) -> None:
    """
    将主站 `api/` auth_users.id 同步为本地 users.id（配额/邀请等仍用本地表）。
    JWT 的 sub 须与平台用户 id 一致；email/phone 来自 token 声明。
    """
    email_n = (email or "").strip().lower() or None
    phone_n = (phone or "").strip() or None
    if email_n == "":
        email_n = None
    if phone_n == "":
        phone_n = None
    now = int(time.time())
    with connect() as conn:
        # Avoid breaking /api/me when admin edited email/phone into conflicts.
        # If email/phone is already bound to a different user, skip syncing that field.
        try:
            if email_n:
                r = conn.execute(
                    _adapt_sql("SELECT id FROM users WHERE email = ? AND id <> ?"),
                    (email_n, int(platform_user_id)),
                ).fetchone()
                if r:
                    email_n = None
            if phone_n:
                r = conn.execute(
                    _adapt_sql("SELECT id FROM users WHERE phone = ? AND id <> ?"),
                    (phone_n, int(platform_user_id)),
                ).fetchone()
                if r:
                    phone_n = None
        except Exception:
            # Best-effort only; never block login path.
            pass
        row = conn.execute(_adapt_sql("SELECT id FROM users WHERE id = ?"), (int(platform_user_id),)).fetchone()
        if row:
            try:
                if _is_pg():
                    conn.execute(
                        """
                        UPDATE users SET
                          email = COALESCE(%s, email),
                          phone = COALESCE(%s, phone)
                        WHERE id = %s
                        """,
                        (email_n, phone_n, int(platform_user_id)),
                    )
                else:
                    conn.execute(
                        """
                        UPDATE users SET
                          email = COALESCE(?, email),
                          phone = COALESCE(?, phone)
                        WHERE id = ?
                        """,
                        (email_n, phone_n, int(platform_user_id)),
                    )
            except Exception:
                # Do not block auth if contact info cannot be synced.
                pass
        else:
            try:
                if _is_pg():
                    conn.execute(
                        """
                        INSERT INTO users (id, email, phone, created_at)
                        VALUES (%s, %s, %s, %s)
                        ON CONFLICT (id) DO UPDATE SET
                          email = COALESCE(EXCLUDED.email, users.email),
                          phone = COALESCE(EXCLUDED.phone, users.phone)
                        """,
                        (int(platform_user_id), email_n, phone_n, now),
                    )
                else:
                    conn.execute(
                        """
                        INSERT INTO users (id, email, phone, created_at) VALUES (?, ?, ?, ?)
                        ON CONFLICT(id) DO UPDATE SET
                          email = COALESCE(excluded.email, users.email),
                          phone = COALESCE(excluded.phone, users.phone)
                        """,
                        (int(platform_user_id), email_n, phone_n, now),
                    )
            except Exception:
                pass
        if _is_pg():
            conn.execute(
                """
                INSERT INTO quota(
                  user_id, plan, monthly_limit, daily_limit,
                  monthly_used, daily_used, month_key, day_key, expires_at, updated_at
                ) VALUES (%s, 'free', %s, %s, 0, 0, %s, %s, NULL, %s)
                ON CONFLICT (user_id) DO NOTHING
                """,
                (
                    int(platform_user_id),
                    settings.free_weekly,
                    settings.free_daily_cap,
                    _week_key(now),
                    _day_key(now),
                    now,
                ),
            )
        else:
            conn.execute(
                """
                INSERT INTO quota(
                  user_id, plan, monthly_limit, daily_limit,
                  monthly_used, daily_used, month_key, day_key, expires_at, updated_at
                ) VALUES (?, 'free', ?, ?, 0, 0, ?, ?, NULL, ?)
                ON CONFLICT(user_id) DO NOTHING
                """,
                (
                    int(platform_user_id),
                    settings.free_weekly,
                    settings.free_daily_cap,
                    _week_key(now),
                    _day_key(now),
                    now,
                ),
            )


def get_quota_status(user_id: int) -> dict:
    now = int(time.time())
    with connect() as conn:
        row = conn.execute("SELECT * FROM quota WHERE user_id = ?", (user_id,)).fetchone()
        if not row:
            # should not happen; create default
            conn.execute(
                """
                INSERT INTO quota(
                  user_id, plan, monthly_limit, daily_limit,
                  monthly_used, daily_used, month_key, day_key, expires_at, updated_at
                ) VALUES (?, 'free', ?, ?, 0, 0, ?, ?, NULL, ?)
                ON CONFLICT(user_id) DO UPDATE SET
                  plan=excluded.plan,
                  monthly_limit=excluded.monthly_limit,
                  daily_limit=excluded.daily_limit,
                  monthly_used=excluded.monthly_used,
                  daily_used=excluded.daily_used,
                  month_key=excluded.month_key,
                  day_key=excluded.day_key,
                  expires_at=excluded.expires_at,
                  updated_at=excluded.updated_at
                """,
                (user_id, settings.free_weekly, settings.free_daily_cap, _week_key(now), _day_key(now), now),
            )
            row = conn.execute("SELECT * FROM quota WHERE user_id = ?", (user_id,)).fetchone()

        week_key = str(row["month_key"])
        day_key = str(row["day_key"])
        weekly_used = int(row["monthly_used"])
        daily_used = int(row["daily_used"])

        # IMPORTANT (MVP ops): do NOT auto-sync per-user limits for free plan here.
        # Admin UI supports raising day/week limits for specific users (e.g. manual grants),
        # and auto-sync would immediately revert those overrides back to defaults (day=5/week=10).
        plan = str(row["plan"])
        cur_weekly_limit = int(row["monthly_limit"])
        cur_daily_limit = int(row["daily_limit"])

        if week_key != _week_key(now) or day_key != _day_key(now):
            # reset counters if needed
            if week_key != _week_key(now):
                weekly_used = 0
                week_key = _week_key(now)
            if day_key != _day_key(now):
                daily_used = 0
                day_key = _day_key(now)
            conn.execute(
                """
                UPDATE quota SET month_key=?, day_key=?, monthly_used=?, daily_used=?, updated_at=?
                WHERE user_id=?
                """,
                (week_key, day_key, weekly_used, daily_used, now, user_id),
            )

        weekly_limit_base = int(cur_weekly_limit)
        daily_limit_base = int(cur_daily_limit)
        expires_at = row["expires_at"]
        # Weekly bonus from invite rewards (per-week, capped)
        wk_start = _week_start_ts(now)
        day_start = _day_start_ts(now)
        bonus_week = 0
        bonus_day = 0
        try:
            rr = conn.execute(
                """
                SELECT COALESCE(SUM(amount), 0) AS s
                FROM reward_ledger
                WHERE inviter_id=? AND created_at>=?
                """,
                (user_id, wk_start),
            ).fetchone()
            bonus_week = int(rr["s"] or 0) if rr else 0
        except Exception:
            bonus_week = 0
        try:
            rr2 = conn.execute(
                """
                SELECT COALESCE(SUM(amount), 0) AS s
                FROM reward_ledger
                WHERE inviter_id=? AND reward_type='invite_first_query_inviter_daily' AND created_at>=?
                """,
                (user_id, day_start),
            ).fetchone()
            bonus_day = int(rr2["s"] or 0) if rr2 else 0
        except Exception:
            bonus_day = 0
        weekly_limit = max(0, weekly_limit_base + max(0, bonus_week))
        daily_limit = max(0, daily_limit_base + max(0, bonus_day))

        remaining_week = max(0, weekly_limit - weekly_used)
        remaining_day = max(0, daily_limit - daily_used)
        remaining = min(remaining_week, remaining_day)
        return {
            "plan": str(row["plan"]),
            "remaining": remaining,
            "remaining_day": remaining_day,
            "remaining_week": remaining_week,
            # backward-compat alias (older UI may show "month")
            "remaining_month": remaining_week,
            "daily_used": daily_used,
            "weekly_used": weekly_used,
            "monthly_used": weekly_used,
            "daily_limit": daily_limit,
            "weekly_limit": weekly_limit,
            "monthly_limit": weekly_limit,
            "weekly_limit_base": weekly_limit_base,
            "weekly_bonus": max(0, bonus_week),
            "daily_limit_base": daily_limit_base,
            "daily_bonus": max(0, bonus_day),
            "expires_at": int(expires_at) if expires_at is not None else None,
        }


def consume_quota(user_id: int, secid: str, period: str, idempotency_key: str, ok: bool) -> dict:
    """
    扣次：由上层决定是否“成功”。
    - 30 秒内对同一 secid+period 去重：应由调用方使用稳定 idempotency_key
    """
    now = int(time.time())
    downgrade_expired_vip_plan(int(user_id))
    with connect() as conn:
        # idempotency
        existing = conn.execute(
            "SELECT result, consumed_at FROM quota_ledger WHERE user_id=? AND idempotency_key=?",
            (user_id, idempotency_key),
        ).fetchone()
        if existing:
            return {"deduped": True, "result": str(existing["result"]), "consumed_at": int(existing["consumed_at"])}

        # Free whitelist (MVP): core indices are always free and should never consume quota.
        # Keep it server-enforced to avoid client-side bypass or UI inconsistencies.
        free_whitelist = {"1.000001", "0.399001", "0.399006", "0.899050", "0.000977"}  # 上证/深成/创业/北证50/浪潮信息
        if ok and str(secid).strip() in free_whitelist:
            conn.execute(
                """
                INSERT INTO quota_ledger(user_id, secid, period, idempotency_key, consumed_at, result)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (user_id, secid, period, idempotency_key, now, "free"),
            )
            return {"deduped": False, "result": "free", "consumed_at": now, "quota": get_quota_status(user_id)}

        had_ok_before = False
        try:
            r0 = conn.execute(
                "SELECT 1 FROM quota_ledger WHERE user_id=? AND result='ok' LIMIT 1",
                (user_id,),
            ).fetchone()
            had_ok_before = bool(r0)
        except Exception:
            had_ok_before = False

        status = get_quota_status(user_id)
        if not ok:
            conn.execute(
                """
                INSERT INTO quota_ledger(user_id, secid, period, idempotency_key, consumed_at, result)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (user_id, secid, period, idempotency_key, now, "failed"),
            )
            return {"deduped": False, "result": "failed", "consumed_at": now, "quota": status}

        if status["remaining"] <= 0:
            conn.execute(
                """
                INSERT INTO quota_ledger(user_id, secid, period, idempotency_key, consumed_at, result)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (user_id, secid, period, idempotency_key, now, "exhausted"),
            )
            return {"deduped": False, "result": "exhausted", "consumed_at": now, "quota": status}

        # update counters
        conn.execute(
            """
            UPDATE quota
            SET monthly_used = monthly_used + 1,
                daily_used = daily_used + 1,
                updated_at = ?
            WHERE user_id = ?
            """,
            (now, user_id),
        )
        conn.execute(
            """
            INSERT INTO quota_ledger(user_id, secid, period, idempotency_key, consumed_at, result)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (user_id, secid, period, idempotency_key, now, "ok"),
        )

        # Invite reward trigger: first successful query after binding
        if not had_ok_before:
            try:
                rel = conn.execute(
                    "SELECT inviter_id FROM invite_relations WHERE invitee_id=?",
                    (user_id,),
                ).fetchone()
                if rel and rel["inviter_id"] is not None:
                    inviter_id = int(rel["inviter_id"])
                    wk_start = _week_start_ts(now)

                    def inviter_awarded_this_week(uid: int) -> int:
                        rr = conn.execute(
                            """
                            SELECT COALESCE(SUM(amount), 0) AS s
                            FROM reward_ledger
                            WHERE inviter_id=? AND reward_type='invite_first_query_inviter' AND created_at>=?
                            """,
                            (uid, wk_start),
                        ).fetchone()
                        return int(rr["s"] or 0) if rr else 0

                    # inviter weekly cap
                    cfg = invite_cfg_effective()
                    cap = max(0, int(cfg.get("invite_weekly_cap", 0)))
                    already = inviter_awarded_this_week(inviter_id)
                    grant_inviter = max(0, int(cfg.get("invite_reward_inviter_weekly", 0)))
                    if cap > 0:
                        grant_inviter = min(grant_inviter, max(0, cap - already))

                    if grant_inviter > 0:
                        # receiver=inviter_id, source=invitee(user_id)
                        if _is_pg():
                            conn.execute(
                                """
                                INSERT INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                ON CONFLICT (inviter_id, invitee_id, reward_type) DO NOTHING
                                """,
                                (inviter_id, user_id, "invite_first_query_inviter", grant_inviter, now),
                            )
                        else:
                            conn.execute(
                                """
                                INSERT OR IGNORE INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                """,
                                (inviter_id, user_id, "invite_first_query_inviter", grant_inviter, now),
                            )

                    # inviter daily bonus (optional)
                    grant_inviter_day = max(0, int(cfg.get("invite_reward_inviter_daily", 0)))
                    if grant_inviter_day > 0:
                        if _is_pg():
                            conn.execute(
                                """
                                INSERT INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                ON CONFLICT (inviter_id, invitee_id, reward_type) DO NOTHING
                                """,
                                (inviter_id, user_id, "invite_first_query_inviter_daily", grant_inviter_day, now),
                            )
                        else:
                            conn.execute(
                                """
                                INSERT OR IGNORE INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                """,
                                (inviter_id, user_id, "invite_first_query_inviter_daily", grant_inviter_day, now),
                            )

                    # invitee welcome bonus (not capped by inviter cap)
                    grant_invitee = max(0, int(cfg.get("invite_reward_invitee_weekly", 0)))
                    if grant_invitee > 0:
                        # receiver=user_id, source=inviter_id
                        if _is_pg():
                            conn.execute(
                                """
                                INSERT INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                ON CONFLICT (inviter_id, invitee_id, reward_type) DO NOTHING
                                """,
                                (user_id, inviter_id, "invite_first_query_invitee", grant_invitee, now),
                            )
                        else:
                            conn.execute(
                                """
                                INSERT OR IGNORE INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                """,
                                (user_id, inviter_id, "invite_first_query_invitee", grant_invitee, now),
                            )

                    grant_invitee_day = max(0, int(cfg.get("invite_reward_invitee_daily", 0)))
                    if grant_invitee_day > 0:
                        if _is_pg():
                            conn.execute(
                                """
                                INSERT INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                ON CONFLICT (inviter_id, invitee_id, reward_type) DO NOTHING
                                """,
                                (user_id, inviter_id, "invite_first_query_invitee_daily", grant_invitee_day, now),
                            )
                        else:
                            conn.execute(
                                """
                                INSERT OR IGNORE INTO reward_ledger(inviter_id, invitee_id, reward_type, amount, created_at)
                                VALUES (?, ?, ?, ?, ?)
                                """,
                                (user_id, inviter_id, "invite_first_query_invitee_daily", grant_invitee_day, now),
                            )
            except Exception:
                # reward is best-effort; do not break quota consumption
                pass

        return {"deduped": False, "result": "ok", "consumed_at": now, "quota": get_quota_status(user_id)}


def kline_cache_get(cache_key: str) -> dict[str, Any] | None:
    now = int(time.time())
    key = str(cache_key or "").strip()
    if not key:
        return None
    with connect() as conn:
        row = conn.execute(
            "SELECT expire_ts, payload_json FROM kline_cache WHERE cache_key=?",
            (key,),
        ).fetchone()
        if not row:
            return None
        exp = int(row["expire_ts"])
        if exp <= now:
            try:
                conn.execute("DELETE FROM kline_cache WHERE cache_key=?", (key,))
            except Exception:
                pass
            return None
        try:
            return json.loads(str(row["payload_json"]))
        except Exception:
            return None


def kline_cache_put(cache_key: str, payload: dict[str, Any], ttl_s: float) -> None:
    key = str(cache_key or "").strip()
    if not key:
        return
    ttl = float(ttl_s or 0)
    if ttl <= 0:
        return
    now = int(time.time())
    exp = now + max(1, int(ttl))
    try:
        s = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    except Exception:
        return
    with connect() as conn:
        try:
            if _is_pg():
                conn.execute(
                    """
                    INSERT INTO kline_cache(cache_key, expire_ts, payload_json, updated_at)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (cache_key) DO UPDATE SET
                      expire_ts=EXCLUDED.expire_ts,
                      payload_json=EXCLUDED.payload_json,
                      updated_at=EXCLUDED.updated_at
                    """,
                    (key, exp, s, now),
                )
            else:
                conn.execute(
                    """
                    INSERT INTO kline_cache(cache_key, expire_ts, payload_json, updated_at)
                    VALUES (?, ?, ?, ?)
                    ON CONFLICT(cache_key) DO UPDATE SET
                      expire_ts=excluded.expire_ts,
                      payload_json=excluded.payload_json,
                      updated_at=excluded.updated_at
                    """,
                    (key, exp, s, now),
                )
        except Exception:
            pass


def admin_list_users(q: str = "", limit: int = 50, offset: int = 0) -> dict[str, Any]:
    qq = (q or "").strip()
    limit = max(1, min(int(limit or 50), 200))
    offset = max(0, int(offset or 0))
    with connect() as conn:
        where = ""
        params: list[Any] = []
        if qq:
            if qq.isdigit():
                where = "WHERE u.id = ? OR u.phone LIKE ?"
                params.extend([int(qq), f"%{qq}%"])
            else:
                where = "WHERE u.email LIKE ? OR u.phone LIKE ?"
                params.extend([f"%{qq}%", f"%{qq}%"])
        rows = conn.execute(
            f"""
            SELECT u.id, u.email, u.phone, u.created_at,
                   q.plan, q.monthly_limit, q.daily_limit, q.monthly_used, q.daily_used, q.month_key, q.day_key, q.expires_at
            FROM users u
            LEFT JOIN quota q ON q.user_id = u.id
            {where}
            ORDER BY u.id DESC
            LIMIT ? OFFSET ?
            """,
            (*params, limit, offset),
        ).fetchall()

        items = []
        for r in rows:
            uid = int(r["id"])
            items.append(
                {
                    "id": uid,
                    "email": str(r["email"]) if r["email"] is not None else "",
                    "phone": str(r["phone"]) if r["phone"] is not None else "",
                    "created_at": int(r["created_at"]),
                    "quota": get_quota_status(uid) if r["plan"] is not None else None,
                }
            )
        return {"items": items, "limit": limit, "offset": offset}


def admin_get_user(uid: int) -> dict[str, Any]:
    uid = int(uid)
    with connect() as conn:
        u = conn.execute("SELECT id, email, phone, created_at FROM users WHERE id=?", (uid,)).fetchone()
        if not u:
            raise ValueError("user not found")
        invite_code = conn.execute("SELECT code FROM invite_codes WHERE user_id=?", (uid,)).fetchone()
        inviter = conn.execute("SELECT inviter_id FROM invite_relations WHERE invitee_id=?", (uid,)).fetchone()
        return {
            "user": {
                "id": int(u["id"]),
                "email": str(u["email"]) if u["email"] is not None else "",
                "phone": str(u["phone"]) if u["phone"] is not None else "",
                "created_at": int(u["created_at"]),
            },
            "quota": get_quota_status(uid),
            "invite": {
                "my_code": str(invite_code["code"]) if invite_code else None,
                "inviter_id": int(inviter["inviter_id"]) if inviter else None,
            },
        }


def admin_update_user_basic(uid: int, *, email: str | None = None, phone: str | None = None) -> dict[str, Any]:
    """
    Update user basic contact fields (email/phone).
    - email normalized to lowercase; empty -> NULL
    - phone trimmed; empty -> NULL
    Uniqueness is enforced by DB constraints.
    """
    uid = int(uid)
    email_n = (email or "").strip().lower() or None
    phone_n = (phone or "").strip().replace(" ", "") or None
    # Basic format guardrails (keep permissive; identity system may use various formats).
    if email_n is not None and ("@" not in email_n or len(email_n) < 6):
        raise ValueError("邮箱格式不正确")
    if phone_n is not None and (len(phone_n) < 6 or len(phone_n) > 32):
        raise ValueError("手机号格式不正确")

    with connect() as conn:
        u = conn.execute("SELECT id FROM users WHERE id=?", (uid,)).fetchone()
        if not u:
            raise ValueError("user not found")
        try:
            conn.execute(
                "UPDATE users SET email=?, phone=? WHERE id=?",
                (email_n, phone_n, uid),
            )
        except Exception as e:
            msg = str(e).lower()
            if "unique" in msg or "unique constraint" in msg:
                raise ValueError("邮箱或手机号已被占用")
            raise
    return admin_get_user(uid)


def get_user_basic(uid: int) -> dict[str, Any]:
    uid = int(uid)
    with connect() as conn:
        u = conn.execute("SELECT id, email, phone, created_at FROM users WHERE id=?", (uid,)).fetchone()
        if not u:
            raise ValueError("user not found")
        return {
            "id": int(u["id"]),
            "email": str(u["email"]) if u["email"] is not None else "",
            "phone": str(u["phone"]) if u["phone"] is not None else "",
            "created_at": int(u["created_at"]),
        }


def admin_set_remaining(uid: int, remaining: int) -> dict[str, Any]:
    uid = int(uid)
    remaining = max(0, int(remaining))
    now = int(time.time())
    status = get_quota_status(uid)
    daily_limit = int(status["daily_limit"])
    monthly_limit = int(status["monthly_limit"])
    # remaining 受 day/month 两个口径共同限制，因此这里把 day/month 都设置到 >= remaining
    new_daily_used = max(0, daily_limit - remaining)
    new_monthly_used = max(0, monthly_limit - remaining)
    with connect() as conn:
        conn.execute(
            """
            UPDATE quota
            SET daily_used=?, monthly_used=?, updated_at=?
            WHERE user_id=?
            """,
            (new_daily_used, new_monthly_used, now, uid),
        )
    return {"quota": get_quota_status(uid)}


def _plan_defaults(plan: str) -> tuple[str, int, int, int | None]:
    """
    Return (normalized_plan, weekly_limit_base, daily_limit_base, expires_at_ts)
    Note: week/month are unified as "weekly" in this MVP schema.
    """
    now = int(time.time())
    p = str(plan or "").strip().lower()
    if not p:
        p = "free"
    if p in ("free", "anon"):
        return ("free", int(settings.free_weekly), int(settings.free_daily_cap), None)
    if p in ("vip", "vip_month", "month", "monthly"):
        # 30 days validity (soft; only used for UI display currently)
        return ("vip_month", int(settings.vip_weekly), int(settings.vip_daily_cap), now + 30 * 86400)
    if p in ("vip_year_999", "vip_year", "year", "yearly"):
        return ("vip_year_999", int(settings.vip_weekly), int(settings.vip_daily_cap), now + 365 * 86400)
    if p in ("vip_trial_99", "vip_trial", "trial", "trial_99"):
        # 体验卡：7 天；额度低于月卡（默认 100/周 + 20/天，约≤100 次/首周），单价不低于月卡折算
        return (
            "vip_trial_99",
            int(settings.vip_trial_weekly),
            int(settings.vip_trial_daily_cap),
            now + 7 * 86400,
        )
    # Custom/legacy plan: keep current limits, do not set expiry.
    return (p, -1, -1, None)


def downgrade_expired_vip_plan(user_id: int) -> None:
    """
    若 VIP 已过期（expires_at < now），单事务写回 free 并记 ops 流水。
    供扣次前与 /api/me 等读路径调用，避免「到期仍显示 VIP」。
    """
    uid = int(user_id)
    now = int(time.time())
    with connect() as conn:
        row = conn.execute(
            "SELECT plan, expires_at, monthly_used, daily_used FROM quota WHERE user_id=?",
            (uid,),
        ).fetchone()
        if not row:
            return
        plan = str(row["plan"])
        if plan not in ("vip_month", "vip_year_999", "vip_trial_99"):
            return
        exp = row["expires_at"]
        if exp is None or int(exp) >= now:
            return
        fp, fw, fd, _ = _plan_defaults("free")
        mu = int(row["monthly_used"])
        du = int(row["daily_used"])
        nu_w = max(0, min(mu, int(fw)))
        nu_d = max(0, min(du, int(fd)))
        before = {"plan": plan, "expires_at": int(exp), "monthly_used": mu, "daily_used": du}
        conn.execute(
            """
            UPDATE quota
            SET plan=?, monthly_limit=?, daily_limit=?, monthly_used=?, daily_used=?, expires_at=NULL, updated_at=?
            WHERE user_id=?
            """,
            (fp, fw, fd, nu_w, nu_d, now, uid),
        )
        after = {"plan": fp, "expires_at": None, "monthly_used": nu_w, "daily_used": nu_d}
        conn.execute(
            """
            INSERT INTO admin_ops_ledger(user_id, actor, action, before_json, after_json, note, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                uid,
                "system",
                "vip_expire",
                json.dumps(before, ensure_ascii=False, separators=(",", ":")),
                json.dumps(after, ensure_ascii=False, separators=(",", ":")),
                "auto downgrade: expires_at passed",
                now,
            ),
        )


def admin_quota_adjust(
    uid: int,
    *,
    actor: str = "admin",
    set_remaining_day: int | None = None,
    set_remaining_week: int | None = None,
    delta_day: int | None = None,
    delta_week: int | None = None,
    plan: str | None = None,
    note: str = "",
) -> dict[str, Any]:
    """
    Admin-only quota adjustment with audit log.
    - set_remaining_*: absolute set remaining counts (>=0)
    - delta_*: relative adjustment on remaining counts (can be negative)
    - plan: switch plan preset (free/vip_month/vip_year_999/vip_trial_99)
    """
    uid = int(uid)
    now = int(time.time())
    actor = str(actor or "admin").strip()[:64] or "admin"
    note = str(note or "").strip()[:200]

    before = get_quota_status(uid)

    with connect() as conn:
        # Fetch raw quota row (we need base limits/used)
        row = conn.execute("SELECT * FROM quota WHERE user_id=?", (uid,)).fetchone()
        if not row:
            raise ValueError("quota not found")

        cur_plan = str(row["plan"])
        cur_weekly_limit_base = int(row["monthly_limit"])
        cur_daily_limit_base = int(row["daily_limit"])
        cur_weekly_used = int(row["monthly_used"])
        cur_daily_used = int(row["daily_used"])

        new_plan = cur_plan
        new_weekly_limit_base = cur_weekly_limit_base
        new_daily_limit_base = cur_daily_limit_base
        new_expires_at = row["expires_at"]

        action_bits: list[str] = []

        if plan is not None:
            np, wk, dy, exp = _plan_defaults(str(plan))
            new_plan = np
            if wk >= 0:
                new_weekly_limit_base = int(wk)
            if dy >= 0:
                new_daily_limit_base = int(dy)
            if exp is not None:
                new_expires_at = int(exp)
            else:
                # free plan clears expiry
                if new_plan == "free":
                    new_expires_at = None
            action_bits.append(f"plan:{cur_plan}->{new_plan}")

        # After potential plan change, recompute remaining based on base limits (ignore bonuses for admin ops)
        def _clamp_used(limit_base: int, used: int) -> int:
            if limit_base < 0:
                return max(0, used)
            return max(0, min(int(used), int(limit_base)))

        new_weekly_used = _clamp_used(new_weekly_limit_base, cur_weekly_used)
        new_daily_used = _clamp_used(new_daily_limit_base, cur_daily_used)

        def _apply_set_remaining(limit_base: int, used: int, remaining: int) -> int:
            if limit_base < 0:
                # unknown limit: treat remaining as "best effort" by adjusting used down/up around 0
                return max(0, int(used))
            # If admin sets remaining beyond current limit, auto-raise the base limit so it can take effect.
            rem = max(0, int(remaining))
            return max(0, int(limit_base) - min(rem, int(limit_base)))

        def _apply_delta_remaining(limit_base: int, used: int, delta: int) -> int:
            if limit_base < 0:
                return max(0, int(used))
            cur_rem = max(0, int(limit_base) - int(used))
            tgt_rem = cur_rem + int(delta)
            tgt_rem = max(0, min(int(tgt_rem), int(limit_base)))
            return max(0, int(limit_base) - int(tgt_rem))

        if set_remaining_day is not None:
            # Auto-raise daily limit if needed so the target remaining is achievable.
            if new_daily_limit_base >= 0:
                new_daily_limit_base = max(int(new_daily_limit_base), max(0, int(set_remaining_day)))
                new_daily_used = _clamp_used(new_daily_limit_base, new_daily_used)
            new_daily_used = _apply_set_remaining(new_daily_limit_base, new_daily_used, int(set_remaining_day))
            action_bits.append("set_remaining_day")
        if set_remaining_week is not None:
            if new_weekly_limit_base >= 0:
                new_weekly_limit_base = max(int(new_weekly_limit_base), max(0, int(set_remaining_week)))
                new_weekly_used = _clamp_used(new_weekly_limit_base, new_weekly_used)
            new_weekly_used = _apply_set_remaining(new_weekly_limit_base, new_weekly_used, int(set_remaining_week))
            action_bits.append("set_remaining_week")
        if delta_day is not None and int(delta_day) != 0:
            if new_daily_limit_base >= 0:
                cur_rem0 = max(0, int(new_daily_limit_base) - int(new_daily_used))
                tgt_rem0 = max(0, cur_rem0 + int(delta_day))
                # Expand limit if needed so +delta can take effect.
                if tgt_rem0 > int(new_daily_limit_base):
                    new_daily_limit_base = int(new_daily_used) + int(tgt_rem0)
                tgt_rem0 = max(0, min(int(tgt_rem0), int(new_daily_limit_base)))
                new_daily_used = max(0, int(new_daily_limit_base) - int(tgt_rem0))
            else:
                new_daily_used = _apply_delta_remaining(new_daily_limit_base, new_daily_used, int(delta_day))
            action_bits.append(f"delta_day:{int(delta_day)}")
        if delta_week is not None and int(delta_week) != 0:
            if new_weekly_limit_base >= 0:
                cur_rem1 = max(0, int(new_weekly_limit_base) - int(new_weekly_used))
                tgt_rem1 = max(0, cur_rem1 + int(delta_week))
                if tgt_rem1 > int(new_weekly_limit_base):
                    new_weekly_limit_base = int(new_weekly_used) + int(tgt_rem1)
                tgt_rem1 = max(0, min(int(tgt_rem1), int(new_weekly_limit_base)))
                new_weekly_used = max(0, int(new_weekly_limit_base) - int(tgt_rem1))
            else:
                new_weekly_used = _apply_delta_remaining(new_weekly_limit_base, new_weekly_used, int(delta_week))
            action_bits.append(f"delta_week:{int(delta_week)}")

        if not action_bits:
            # no-op but still return current quota
            return {"quota": get_quota_status(uid)}

        # Persist quota changes
        conn.execute(
            """
            UPDATE quota
            SET plan=?,
                monthly_limit=?,
                daily_limit=?,
                monthly_used=?,
                daily_used=?,
                expires_at=?,
                updated_at=?
            WHERE user_id=?
            """,
            (
                str(new_plan),
                int(new_weekly_limit_base),
                int(new_daily_limit_base),
                int(new_weekly_used),
                int(new_daily_used),
                new_expires_at,
                now,
                uid,
            ),
        )

        after = get_quota_status(uid)
        conn.execute(
            """
            INSERT INTO admin_ops_ledger(user_id, actor, action, before_json, after_json, note, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                uid,
                actor,
                ",".join(action_bits)[:120],
                json.dumps(before, ensure_ascii=False, separators=(",", ":")),
                json.dumps(after, ensure_ascii=False, separators=(",", ":")),
                note,
                now,
            ),
        )

    return {"quota": get_quota_status(uid)}


def admin_list_ops_ledger(user_id: int, limit: int = 50) -> dict[str, Any]:
    user_id = int(user_id)
    limit = max(1, min(int(limit or 50), 200))
    with connect() as conn:
        rows = conn.execute(
            """
            SELECT id, user_id, actor, action, before_json, after_json, note, created_at
            FROM admin_ops_ledger
            WHERE user_id=?
            ORDER BY id DESC
            LIMIT ?
            """,
            (user_id, limit),
        ).fetchall()
        items = []
        for r in rows:
            items.append(
                {
                    "id": int(r["id"]),
                    "user_id": int(r["user_id"]),
                    "actor": str(r["actor"]),
                    "action": str(r["action"]),
                    "note": str(r["note"] or ""),
                    "created_at": int(r["created_at"]),
                }
            )
        return {"items": items, "limit": limit}


def admin_list_quota_ledger(user_id: int, limit: int = 50) -> dict[str, Any]:
    user_id = int(user_id)
    limit = max(1, min(int(limit or 50), 200))
    with connect() as conn:
        rows = conn.execute(
            """
            SELECT id, user_id, secid, period, consumed_at, result
            FROM quota_ledger
            WHERE user_id=?
            ORDER BY id DESC
            LIMIT ?
            """,
            (user_id, limit),
        ).fetchall()
        items = [
            {
                "id": int(r["id"]),
                "user_id": int(r["user_id"]),
                "secid": str(r["secid"]),
                "period": str(r["period"]),
                "consumed_at": int(r["consumed_at"]),
                "result": str(r["result"]),
            }
            for r in rows
        ]
        return {"items": items, "limit": limit}


def _admin_pay_orders_where_params(
    *,
    user_id: int = 0,
    status: str = "",
    plan: str = "",
    q: str = "",
) -> tuple[str, list[Any]]:
    """构建 pay_orders 管理端筛选 WHERE 与参数（SQLite / PG 占位符由 connect 适配）。"""
    uid_f = int(user_id or 0)
    st = (status or "").strip()
    pl = (plan or "").strip()
    qq = (q or "").strip()
    clauses: list[str] = []
    params: list[Any] = []
    if uid_f > 0:
        clauses.append("user_id = ?")
        params.append(uid_f)
    if st:
        clauses.append("status = ?")
        params.append(st)
    if pl:
        clauses.append("plan = ?")
        params.append(pl)
    if qq:
        like = f"%{qq}%"
        or_parts = ["out_trade_no LIKE ?", "COALESCE(CAST(transaction_id AS TEXT), '') LIKE ?"]
        params.extend([like, like])
        if qq.isdigit():
            try:
                n = int(qq)
                if n > 0:
                    or_parts.append("user_id = ?")
                    params.append(n)
            except ValueError:
                pass
        clauses.append("(" + " OR ".join(or_parts) + ")")
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    return where, params


def _admin_pay_order_row_dict(r: Any) -> dict[str, Any]:
    return {
        "id": int(r["id"]),
        "out_trade_no": str(r["out_trade_no"] or ""),
        "user_id": int(r["user_id"]),
        "plan": str(r["plan"] or ""),
        "amount_fen": int(r["amount_fen"] or 0),
        "channel": str(r["channel"] or ""),
        "status": str(r["status"] or ""),
        "transaction_id": str(r["transaction_id"] or "") if r["transaction_id"] is not None else "",
        "created_at": int(r["created_at"] or 0),
        "updated_at": int(r["updated_at"] or 0),
        "has_code_url": bool(int(_row_get(r, "has_code_url") or 0)),
    }


def admin_list_pay_orders(
    *,
    user_id: int = 0,
    status: str = "",
    plan: str = "",
    q: str = "",
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    """管理端：VIP/支付订单列表（pay_orders）；q 匹配商户单号 / 微信单号 / 纯数字时 user_id。"""
    limit = max(1, min(int(limit or 50), 200))
    offset = max(0, int(offset or 0))
    where, params = _admin_pay_orders_where_params(user_id=user_id, status=status, plan=plan, q=q)
    with connect() as conn:
        cnt_row = conn.execute(f"SELECT COUNT(1) AS c FROM pay_orders{where}", tuple(params)).fetchone()
        total = int(_row_get(cnt_row, "c") or 0)
        rows = conn.execute(
            f"""
            SELECT id, out_trade_no, user_id, plan, amount_fen, channel, status,
                   transaction_id, created_at, updated_at,
                   CASE WHEN code_url IS NOT NULL AND LENGTH(TRIM(CAST(code_url AS TEXT))) > 0 THEN 1 ELSE 0 END AS has_code_url
            FROM pay_orders
            {where}
            ORDER BY id DESC
            LIMIT ? OFFSET ?
            """,
            (*params, limit, offset),
        ).fetchall()
        items = [_admin_pay_order_row_dict(r) for r in rows]
        return {"items": items, "total": total, "limit": limit, "offset": offset}


def admin_export_pay_orders_rows(
    *,
    user_id: int = 0,
    status: str = "",
    plan: str = "",
    q: str = "",
    cap: int = 5000,
) -> list[dict[str, Any]]:
    """导出用：同筛选条件，按 id 倒序最多 cap 条。"""
    cap = max(1, min(int(cap or 5000), 10000))
    where, params = _admin_pay_orders_where_params(user_id=user_id, status=status, plan=plan, q=q)
    with connect() as conn:
        rows = conn.execute(
            f"""
            SELECT id, out_trade_no, user_id, plan, amount_fen, channel, status,
                   transaction_id, created_at, updated_at,
                   CASE WHEN code_url IS NOT NULL AND LENGTH(TRIM(CAST(code_url AS TEXT))) > 0 THEN 1 ELSE 0 END AS has_code_url
            FROM pay_orders
            {where}
            ORDER BY id DESC
            LIMIT ?
            """,
            (*params, cap),
        ).fetchall()
        return [_admin_pay_order_row_dict(r) for r in rows]


def admin_operator_list_enabled_phones_from_db() -> list[str]:
    """启用的分管/总管（库表）；手机号已规范为纯数字。"""
    from .admin_otp import normalize_admin_phone

    with connect() as conn:
        rows = conn.execute(
            _adapt_sql("SELECT phone FROM admin_operators WHERE enabled = 1"),
            (),
        ).fetchall()
    out: list[str] = []
    for r in rows or []:
        ph = _row_get(r, "phone")
        if not ph:
            continue
        p = normalize_admin_phone(str(ph))
        if p:
            out.append(p)
    return out


def admin_operator_role_for_phone(phone: str) -> tuple[str, int]:
    """返回 (role, perm_flags)。仅 env 白名单、无表行时视为 super。"""
    from .admin_otp import normalize_admin_phone, parse_admin_otp_env_phones

    p = normalize_admin_phone(phone)
    with connect() as conn:
        row = conn.execute(
            _adapt_sql(
                "SELECT role, perm_flags FROM admin_operators WHERE phone = ? AND enabled = 1 LIMIT 1"
            ),
            (p,),
        ).fetchone()
    if row:
        return str(_row_get(row, "role") or "deputy"), int(_row_get(row, "perm_flags") or 0)
    if p in parse_admin_otp_env_phones():
        return "super", 0x7FFFFFFF
    return "deputy", 0


def admin_config_get_all() -> dict[str, str]:
    with connect() as conn:
        rows = conn.execute("SELECT key, value FROM admin_config").fetchall()
    out: dict[str, str] = {}
    for r in rows:
        out[str(r["key"])] = str(r["value"])
    return out


def admin_config_get(key: str) -> str | None:
    k = str(key or "").strip()
    if not k:
        return None
    with connect() as conn:
        row = conn.execute("SELECT value FROM admin_config WHERE key=?", (k,)).fetchone()
    if not row:
        return None
    return str(row["value"])


def admin_config_set(key: str, value: str) -> dict[str, Any]:
    k = str(key or "").strip()
    if not k:
        raise ValueError("missing key")
    v = str(value if value is not None else "").strip()
    if not v:
        with connect() as conn:
            conn.execute("DELETE FROM admin_config WHERE key=?", (k,))
        return {"item": None, "deleted": True, "key": k}
    now = int(time.time())
    with connect() as conn:
        if _is_pg():
            conn.execute(
                """
                INSERT INTO admin_config(key, value, updated_at)
                VALUES (%s, %s, %s)
                ON CONFLICT (key) DO UPDATE SET
                  value=EXCLUDED.value,
                  updated_at=EXCLUDED.updated_at
                """,
                (k, v, now),
            )
            row = conn.execute("SELECT key, value, updated_at FROM admin_config WHERE key=%s", (k,)).fetchone()
        else:
            conn.execute(
                """
                INSERT INTO admin_config(key, value, updated_at)
                VALUES (?, ?, ?)
                ON CONFLICT(key) DO UPDATE SET
                  value=excluded.value,
                  updated_at=excluded.updated_at
                """,
                (k, v, now),
            )
            row = conn.execute("SELECT key, value, updated_at FROM admin_config WHERE key=?", (k,)).fetchone()
    return {"item": dict(row) if row else {"key": k, "value": v, "updated_at": now}}


def _cfg_int(key: str, default: int) -> int:
    try:
        v = admin_config_get(key)
        if v is None or str(v).strip() == "":
            return int(default)
        return int(float(str(v).strip()))
    except Exception:
        return int(default)


def _cfg_float(key: str, default: float) -> float:
    try:
        v = admin_config_get(key)
        if v is None or str(v).strip() == "":
            return float(default)
        return float(str(v).strip())
    except Exception:
        return float(default)


def _agent_commission_enabled() -> bool:
    return bool(_cfg_int("agent_commission_enabled", 1) == 1)


def _agent_commission_rate_normal() -> float:
    r = float(_cfg_float("agent_commission_rate_normal", 0.20))
    if r < 0:
        r = 0.0
    if r > 0.9:
        r = 0.9
    return r


def _agent_settle_delay_days() -> int:
    d = int(_cfg_int("agent_settle_delay_days", 7))
    return max(0, min(d, 90))


def agent_get_status(user_id: int) -> dict[str, Any] | None:
    uid = int(user_id)
    with connect() as conn:
        row = conn.execute(
            "SELECT user_id, level, expires_at, updated_at FROM agent_status WHERE user_id=?",
            (uid,),
        ).fetchone()
        if not row:
            return None
        return {
            "user_id": int(row["user_id"]),
            "level": str(row["level"]),
            "expires_at": int(row["expires_at"]) if row["expires_at"] is not None else None,
            "updated_at": int(row["updated_at"]),
        }


def _agent_is_active_in_conn(conn: Any, user_id: int, now: int) -> bool:
    uid = int(user_id)
    row = conn.execute("SELECT level, expires_at FROM agent_status WHERE user_id=?", (uid,)).fetchone()
    if not row:
        return False
    if str(row["level"] or "").strip().lower() not in ("normal", "senior", "gold"):
        return False
    exp = row["expires_at"]
    if exp is None:
        return True
    try:
        return int(exp) >= int(now)
    except Exception:
        return False


def _agent_upsert_in_conn(conn: Any, user_id: int, level: str, expires_at: int | None, now: int) -> None:
    uid = int(user_id)
    lvl = str(level or "").strip().lower() or "normal"
    if _is_pg():
        conn.execute(
            """
            INSERT INTO agent_status(user_id, level, expires_at, updated_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT (user_id) DO UPDATE SET
              level=EXCLUDED.level,
              expires_at=EXCLUDED.expires_at,
              updated_at=EXCLUDED.updated_at
            """,
            (uid, lvl, int(expires_at) if expires_at is not None else None, int(now)),
        )
    else:
        conn.execute(
            """
            INSERT INTO agent_status(user_id, level, expires_at, updated_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(user_id) DO UPDATE SET
              level=excluded.level,
              expires_at=excluded.expires_at,
              updated_at=excluded.updated_at
            """,
            (uid, lvl, int(expires_at) if expires_at is not None else None, int(now)),
        )


def _commission_insert_in_conn(
    conn: Any,
    *,
    out_trade_no: str,
    agent_user_id: int,
    buyer_user_id: int,
    plan: str,
    amount_fen: int,
    rate: float,
    commission_fen: int,
    eligible_at: int,
    now: int,
) -> bool:
    """Return True if inserted, False if already exists (idempotent)."""
    otn = str(out_trade_no or "").strip()
    if not otn:
        return False
    if _is_pg():
        row = conn.execute(
            """
            INSERT INTO commission_ledger(
              out_trade_no, agent_user_id, buyer_user_id, plan, amount_fen, rate, commission_fen,
              eligible_at, status, paid_at, paid_note, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', NULL, '', ?, ?)
            ON CONFLICT (out_trade_no) DO NOTHING
            RETURNING out_trade_no
            """,
            (
                otn,
                int(agent_user_id),
                int(buyer_user_id),
                str(plan),
                int(amount_fen),
                float(rate),
                int(commission_fen),
                int(eligible_at),
                int(now),
                int(now),
            ),
        ).fetchone()
        return bool(row)
    conn.execute(
        """
        INSERT OR IGNORE INTO commission_ledger(
          out_trade_no, agent_user_id, buyer_user_id, plan, amount_fen, rate, commission_fen,
          eligible_at, status, paid_at, paid_note, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', NULL, '', ?, ?)
        """,
        (
            otn,
            int(agent_user_id),
            int(buyer_user_id),
            str(plan),
            int(amount_fen),
            float(rate),
            int(commission_fen),
            int(eligible_at),
            int(now),
            int(now),
        ),
    )
    return True


def commission_generate_for_order(out_trade_no: str) -> dict[str, Any]:
    """Admin/manual: generate ledger for a paid order (idempotent)."""
    now = int(time.time())
    otn = str(out_trade_no or "").strip()
    if not otn:
        raise ValueError("missing out_trade_no")
    with connect() as conn:
        row = conn.execute("SELECT * FROM pay_orders WHERE out_trade_no=?", (otn,)).fetchone()
        if not row:
            raise ValueError("order_not_found")
        if str(row["status"]) != "paid":
            raise ValueError("order_not_paid")
        plan = str(row["plan"])
        if plan != "vip_year_999":
            return {"ok": True, "skipped": True, "reason": "plan_not_commissioned"}
        buyer_id = int(row["user_id"])
        inviter_id = None
        try:
            rel = conn.execute(
                "SELECT inviter_id FROM invite_relations WHERE invitee_id=?",
                (buyer_id,),
            ).fetchone()
            if rel and rel["inviter_id"] is not None:
                inviter_id = int(rel["inviter_id"])
        except Exception:
            inviter_id = None
        if not inviter_id:
            return {"ok": True, "skipped": True, "reason": "no_inviter"}
        if not _agent_commission_enabled():
            return {"ok": True, "skipped": True, "reason": "commission_disabled"}
        if not _agent_is_active_in_conn(conn, inviter_id, now):
            return {"ok": True, "skipped": True, "reason": "inviter_not_active_agent"}
        rate = _agent_commission_rate_normal()
        amount_fen = int(row["amount_fen"])
        commission_fen = int(round(float(amount_fen) * float(rate)))
        delay_days = _agent_settle_delay_days()
        eligible_at = int((row["paid_at"] or now) + delay_days * 86400)
        inserted = _commission_insert_in_conn(
            conn,
            out_trade_no=otn,
            agent_user_id=inviter_id,
            buyer_user_id=buyer_id,
            plan=plan,
            amount_fen=amount_fen,
            rate=rate,
            commission_fen=commission_fen,
            eligible_at=eligible_at,
            now=now,
        )
        return {
            "ok": True,
            "inserted": bool(inserted),
            "agent_user_id": int(inviter_id),
            "buyer_user_id": int(buyer_id),
        }


def admin_list_commissions(
    *,
    status: str = "",
    agent_user_id: int = 0,
    q: str = "",
    limit: int = 50,
    offset: int = 0,
    eligible_only: bool = False,
) -> dict[str, Any]:
    limit = max(1, min(int(limit or 50), 200))
    offset = max(0, int(offset or 0))
    st = str(status or "").strip().lower()
    uid = int(agent_user_id or 0)
    qv = str(q or "").strip()
    now = int(time.time())
    clauses: list[str] = []
    params: list[Any] = []
    if st:
        clauses.append("status = ?")
        params.append(st)
    if uid > 0:
        clauses.append("agent_user_id = ?")
        params.append(uid)
    if qv:
        clauses.append("(out_trade_no LIKE ? OR CAST(agent_user_id AS TEXT)=? OR CAST(buyer_user_id AS TEXT)=?)")
        params.extend([f"%{qv}%", qv, qv])
    if eligible_only:
        clauses.append("status='pending' AND eligible_at <= ?")
        params.append(now)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    with connect() as conn:
        rows = conn.execute(
            f"""
            SELECT id, out_trade_no, agent_user_id, buyer_user_id, plan, amount_fen, rate, commission_fen,
                   eligible_at, status, paid_at, paid_note, created_at, updated_at
            FROM commission_ledger
            {where}
            ORDER BY id DESC
            LIMIT ? OFFSET ?
            """,
            (*params, limit, offset),
        ).fetchall()
        items = []
        for r in rows:
            items.append(
                {
                    "id": int(r["id"]),
                    "out_trade_no": str(r["out_trade_no"]),
                    "agent_user_id": int(r["agent_user_id"]),
                    "buyer_user_id": int(r["buyer_user_id"]),
                    "plan": str(r["plan"]),
                    "amount_fen": int(r["amount_fen"]),
                    "rate": float(r["rate"]),
                    "commission_fen": int(r["commission_fen"]),
                    "eligible_at": int(r["eligible_at"]),
                    "status": str(r["status"]),
                    "paid_at": int(r["paid_at"]) if r["paid_at"] is not None else None,
                    "paid_note": str(r["paid_note"] or ""),
                    "created_at": int(r["created_at"]),
                    "updated_at": int(r["updated_at"]),
                }
            )
        return {"items": items, "limit": limit, "offset": offset}


def admin_mark_commissions_paid(agent_user_id: int, *, note: str = "") -> dict[str, Any]:
    """Mark all eligible pending commissions for agent as paid (manual settlement)."""
    now = int(time.time())
    uid = int(agent_user_id)
    if uid <= 0:
        raise ValueError("invalid agent_user_id")
    note2 = str(note or "").strip()[:120]
    with connect() as conn:
        rows = conn.execute(
            """
            SELECT id, commission_fen FROM commission_ledger
            WHERE agent_user_id=? AND status='pending' AND eligible_at<=?
            """,
            (uid, now),
        ).fetchall()
        total = sum(int(r["commission_fen"]) for r in rows)
        if not rows:
            return {"ok": True, "count": 0, "total_fen": 0}
        conn.execute(
            """
            UPDATE commission_ledger
            SET status='paid', paid_at=?, paid_note=?, updated_at=?
            WHERE agent_user_id=? AND status='pending' AND eligible_at<=?
            """,
            (now, note2, now, uid, now),
        )
        return {"ok": True, "count": len(rows), "total_fen": int(total), "paid_at": now}


def invite_summary_for_user(inviter_id: int) -> dict[str, int]:
    inviter_id = int(inviter_id)
    with connect() as conn:
        total_row = conn.execute(
            "SELECT COUNT(1) AS c FROM invite_relations WHERE inviter_id=?",
            (inviter_id,),
        ).fetchone()
        total = int(total_row["c"] or 0) if total_row else 0

        activated_row = conn.execute(
            """
            SELECT COUNT(1) AS c
            FROM invite_relations r
            WHERE r.inviter_id=?
              AND EXISTS (
                SELECT 1 FROM quota_ledger q
                WHERE q.user_id=r.invitee_id AND q.result='ok'
                LIMIT 1
              )
            """,
            (inviter_id,),
        ).fetchone()
        activated = int(activated_row["c"] or 0) if activated_row else 0

        rewarded_row = conn.execute(
            """
            SELECT COUNT(DISTINCT invitee_id) AS c
            FROM reward_ledger
            WHERE inviter_id=?
              AND reward_type='invite_first_query_inviter'
            """,
            (inviter_id,),
        ).fetchone()
        rewarded = int(rewarded_row["c"] or 0) if rewarded_row else 0

    return {"total": total, "activated": activated, "rewarded": rewarded}


def invite_list_for_user(inviter_id: int, limit: int = 50) -> list[dict[str, Any]]:
    inviter_id = int(inviter_id)
    limit = max(1, min(int(limit or 50), 200))
    with connect() as conn:
        rows = conn.execute(
            """
            SELECT
              r.invitee_id,
              r.created_at,
              u.email AS invitee_email,
              u.phone AS invitee_phone,
              EXISTS(SELECT 1 FROM quota_ledger q WHERE q.user_id=r.invitee_id AND q.result='ok' LIMIT 1) AS activated,
              EXISTS(SELECT 1 FROM reward_ledger w WHERE w.inviter_id=r.inviter_id AND w.invitee_id=r.invitee_id AND w.reward_type='invite_first_query_inviter' LIMIT 1) AS rewarded,
              (
                SELECT COALESCE(SUM(w2.amount), 0)
                FROM reward_ledger w2
                WHERE w2.inviter_id=r.inviter_id
                  AND w2.invitee_id=r.invitee_id
                  AND w2.reward_type IN ('invite_first_query_inviter','invite_first_query_inviter_daily')
              ) AS reward_amount
            FROM invite_relations r
            LEFT JOIN users u ON u.id=r.invitee_id
            WHERE r.inviter_id=?
            ORDER BY r.created_at DESC
            LIMIT ?
            """,
            (inviter_id, limit),
        ).fetchall()

    items: list[dict[str, Any]] = []
    for r in rows:
        email = str(r["invitee_email"] or "")
        phone = str(r["invitee_phone"] or "")
        invitee = email or phone or f"user#{int(r['invitee_id'])}"
        items.append(
            {
                "invitee_id": int(r["invitee_id"]),
                "invitee": invitee,
                "created_at": int(r["created_at"]),
                "activated": bool(int(r["activated"] or 0)),
                "rewarded": bool(int(r["rewarded"] or 0)),
                "reward_amount": int(r["reward_amount"] or 0),
            }
        )
    return items


def pay_user_has_paid_trial(user_id: int) -> bool:
    """同一用户是否已成功购买过体验卡（以已支付订单为准，限购 1 次）。"""
    uid = int(user_id)
    with connect() as conn:
        row = conn.execute(
            "SELECT 1 AS x FROM pay_orders WHERE user_id=? AND plan=? AND status='paid' LIMIT 1",
            (uid, "vip_trial_99"),
        ).fetchone()
        return bool(row)


def pay_mk_out_trade_no(user_id: int) -> str:
    now = int(time.time())
    tail = secrets.token_hex(4)
    s = f"M{int(user_id)}{now}{tail}"
    return s[:32]


def pay_order_create(
    user_id: int,
    *,
    out_trade_no: str,
    plan: str,
    amount_fen: int,
    channel: str = "wechat",
    code_url: str | None,
) -> None:
    now = int(time.time())
    uid = int(user_id)
    with connect() as conn:
        conn.execute(
            """
            INSERT INTO pay_orders(
              out_trade_no, user_id, plan, amount_fen, channel, status, code_url, transaction_id, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, 'pending', ?, NULL, ?, ?)
            """,
            (str(out_trade_no), uid, str(plan), int(amount_fen), str(channel or "wechat"), code_url, now, now),
        )


def pay_order_attach_code_url(out_trade_no: str, code_url: str) -> None:
    now = int(time.time())
    with connect() as conn:
        conn.execute(
            "UPDATE pay_orders SET code_url=?, updated_at=? WHERE out_trade_no=?",
            (str(code_url), now, str(out_trade_no)),
        )


def _paid_plan_period_seconds(np: str) -> int:
    if np == "vip_month":
        return 30 * 86400
    if np == "vip_year_999":
        return 365 * 86400
    if np == "vip_trial_99":
        return 7 * 86400
    raise ValueError("unknown paid plan for period")


def _fulfill_paid_plan_in_conn(conn: Any, user_id: int, raw_plan: str, note: str, now: int) -> None:
    uid = int(user_id)
    np, wk, dy, _ = _plan_defaults(raw_plan)
    if np not in ("vip_month", "vip_year_999", "vip_trial_99"):
        raise ValueError("invalid paid plan")
    period = _paid_plan_period_seconds(np)

    row = conn.execute("SELECT * FROM quota WHERE user_id=?", (uid,)).fetchone()
    if not row:
        raise ValueError("quota not found")

    cur_plan = str(row["plan"])
    cur_weekly_limit = int(row["monthly_limit"])
    cur_daily_limit = int(row["daily_limit"])
    cur_weekly_used = int(row["monthly_used"])
    cur_daily_used = int(row["daily_used"])
    exp = row["expires_at"]

    new_weekly = int(wk) if wk >= 0 else cur_weekly_limit
    new_daily = int(dy) if dy >= 0 else cur_daily_limit

    if cur_plan == np and exp is not None:
        base = max(now, int(exp))
        new_exp = int(base + period)
    else:
        new_exp = int(now + period)

    def _clamp_used(limit_base: int, used: int) -> int:
        if limit_base < 0:
            return max(0, int(used))
        return max(0, min(int(used), int(limit_base)))

    nu_w = _clamp_used(new_weekly, cur_weekly_used)
    nu_d = _clamp_used(new_daily, cur_daily_used)

    before = {
        "plan": cur_plan,
        "monthly_limit": cur_weekly_limit,
        "daily_limit": cur_daily_limit,
        "monthly_used": cur_weekly_used,
        "daily_used": cur_daily_used,
        "expires_at": int(exp) if exp is not None else None,
    }
    conn.execute(
        """
        UPDATE quota
        SET plan=?, monthly_limit=?, daily_limit=?, monthly_used=?, daily_used=?, expires_at=?, updated_at=?
        WHERE user_id=?
        """,
        (np, new_weekly, new_daily, nu_w, nu_d, new_exp, now, uid),
    )
    after = {
        "plan": np,
        "monthly_limit": new_weekly,
        "daily_limit": new_daily,
        "monthly_used": nu_w,
        "daily_used": nu_d,
        "expires_at": new_exp,
    }
    # Gift agent status for VIP year (MVP): buying vip_year_999 grants normal agent with same expiry.
    if np == "vip_year_999":
        _agent_upsert_in_conn(conn, uid, "normal", int(new_exp), now)
    conn.execute(
        """
        INSERT INTO admin_ops_ledger(user_id, actor, action, before_json, after_json, note, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            uid,
            "wechat_pay",
            "billing:vip",
            json.dumps(before, ensure_ascii=False, separators=(",", ":")),
            json.dumps(after, ensure_ascii=False, separators=(",", ":")),
            str(note or "")[:200],
            now,
        ),
    )


def pay_order_try_fulfill_wechat(out_trade_no: str, transaction_id: str, amount_fen: int) -> dict[str, Any]:
    """
    微信回调内调用：校验金额、幂等更新订单并发 VIP。
    """
    now = int(time.time())
    otn = str(out_trade_no or "").strip()
    txid = str(transaction_id or "").strip()
    if not otn or not txid:
        return {"ok": False, "error": "missing_trade_refs"}

    with connect() as conn:
        row = conn.execute("SELECT * FROM pay_orders WHERE out_trade_no=?", (otn,)).fetchone()
        if not row:
            return {"ok": False, "error": "order_not_found"}
        if str(row["status"]) == "paid":
            if row["transaction_id"] and str(row["transaction_id"]) == txid:
                return {"ok": True, "duplicate": True}
            return {"ok": False, "error": "order_already_paid"}

        if int(row["amount_fen"]) != int(amount_fen):
            return {"ok": False, "error": "amount_mismatch"}

        uid = int(row["user_id"])
        plan = str(row["plan"])
        _fulfill_paid_plan_in_conn(conn, uid, plan, f"wechat:{otn}", now)

        # Bind referrer (invite) into order for future settlement/reporting.
        inviter_id: int | None = None
        try:
            rel = conn.execute(
                "SELECT inviter_id FROM invite_relations WHERE invitee_id=?",
                (uid,),
            ).fetchone()
            if rel and rel["inviter_id"] is not None:
                inviter_id = int(rel["inviter_id"])
        except Exception:
            inviter_id = None
        conn.execute(
            "UPDATE pay_orders SET status=?, transaction_id=?, paid_at=?, referrer_user_id=?, updated_at=? WHERE out_trade_no=?",
            ("paid", txid, now, inviter_id, now, otn),
        )

        # Commission (MVP): vip_year_999 only; manual settlement; idempotent insert on out_trade_no.
        if plan == "vip_year_999" and inviter_id and _agent_commission_enabled():
            try:
                if _agent_is_active_in_conn(conn, int(inviter_id), now):
                    rate = _agent_commission_rate_normal()
                    commission_fen = int(round(float(amount_fen) * float(rate)))
                    eligible_at = int(now + _agent_settle_delay_days() * 86400)
                    _commission_insert_in_conn(
                        conn,
                        out_trade_no=otn,
                        agent_user_id=int(inviter_id),
                        buyer_user_id=uid,
                        plan=plan,
                        amount_fen=int(amount_fen),
                        rate=rate,
                        commission_fen=commission_fen,
                        eligible_at=eligible_at,
                        now=now,
                    )
            except Exception:
                # Never fail payment fulfill due to commission; admin can regenerate later.
                pass

    return {"ok": True, "duplicate": False}

